<?php include dirname(__DIR__) . DIRECTORY_SEPARATOR . 'layouts' . DIRECTORY_SEPARATOR . 'header.phtml'; ?>

<div class="account">
    <form method="POST" action="">
        <div class="account-wrapper">

            <label for="password">Password: </label>
            <input type="password" name="password">

            <label for="newpassword">New Password: </label>
            <input type="password" name="newpassword">

            <input type="submit" name="submit" value="Update">

            <a class="remove-link" href="../ManagementController/removeAcc?id=<?php echo $_SESSION['userID']; ?>">Remove Account</a>
            </div>
        </div>
    </form>
</div>
