<?php include dirname(__DIR__) . DIRECTORY_SEPARATOR . 'layouts' . DIRECTORY_SEPARATOR . 'header.phtml'; ?>

<form method="post" action="" enctype="multipart/form-data">
    <input type="file" name="filename[]" id="file" multiple>

    <input type="submit" name="submit" value="Upload">
</form>

<table>
    <?php

    if (isset($images)) {
        foreach ($images as $image) {
            ?>
            <tr>
                <td><img src="<?php echo '../public/media/' . $image['filename']; ?>"</td>

                <td><?php echo $image['username']; ?></td>

                <td><?php echo $image['email']; ?></td>
                <td>
                    <?php if ($image['username'] == $_SESSION['username']) {

                        ?>
                    <a href="../ManagementController/removeImage?id=<?php echo $image['id']; ?>">Delete</a>
                <?php
                    }
                     ?>
                </td>
            </tr>
    <?php
        }
    }

    ?>
</table>
