<?php include dirname(__DIR__) . DIRECTORY_SEPARATOR . 'layouts' . DIRECTORY_SEPARATOR . 'header.phtml'; ?>

<div class="login">
    <form action="" method="POST">
        <div class="login-container">

            <label for="username">Username: </label>
            <input type="text" name="username" value="<?php if (isset($_COOKIE['remember_user'])) echo $_COOKIE['remember_user']; ?>">

            <label for="email">Email:</label>
            <input type="email" name="email">

            <label for="password">Password:</label>
            <input type="password" name="password">

            <label for="remember_me">
                <input type="checkbox" name="remember_me" id="remember_me" value="checked"/>
                Remember me
            </label>

            <input type="submit" name="submit" value="submit">
            <p>Are you new? <span><a class="register-question" href="./register">Register!</a></span></p>
        </div>
    </form>
</div>


