<?php include dirname(__DIR__) . DIRECTORY_SEPARATOR . 'layouts' . DIRECTORY_SEPARATOR . 'header.phtml'; ?>

<form action="" method="POST">

    <div class="form">
        <label for="firstname">Firstname: </label>
        <input type="text" name="firstname" class="form-control <?php if(isset($data['firstname_err'])) (!empty($data['firstname_err'])) ? 'invalid' : ''; ?> value="<?php if(isset($data['firstname'])) echo $data['firstname']; ?>">
        <span class="invalid-response"><?php if (isset($data['firstname_err'])) echo $data['firstname_err']; ?></span>
    </div>

    <div class="form">
        <label for="lastname">Lastname: </label>
        <input type="text" name="lastname" class="form-control <?php if (isset($data['lastname_err'])) (!empty($data['lastname_err'])) ? 'invalid' : ''; ?> value="<?php if (isset($data['lastname'])) echo $data['lastname']; ?>">
        <span class="invalid-response"><?php if (isset($data['lastname_err'])) echo $data['lastname_err']; ?></span>
    </div>

    <div class="form">
        <label for="username">Username: </label>
        <input type="text" name="username">

    </div>
    <div class="form">
        <label for="email">Email: </label>
        <input type="email" name="email">

    </div>

    <div class="form">
        <label for="password">Password: </label>
        <input type="password" name="password">

    </div>

    <div class="form">
        <label for="rppassword">Repeat Password: </label>
        <input type="password" name="repeat-password">

    </div>

    <input type="submit" name="submit" value="submit">
</form>