<?php include dirname(__DIR__) . DIRECTORY_SEPARATOR . 'layouts' . DIRECTORY_SEPARATOR . 'header.phtml'; ?>

<div class="signup">
    <form action="" method="POST">
        <div class="signup-container">

            <label for="firstname">Firstname: </label>
            <input type="text" name="firstname" class="form-control <?php if(isset($data['firstname_err'])) (!empty($data['firstname_err'])) ? 'invalid' : ''; ?> value="<?php if (isset($data['firstname'])) echo $data['firstname']; ?>">
            <span class="invalid-response"><?php if (isset($data['firstname_err'])) echo $data['firstname_err']; ?></span>

            <label for="lastname">Lastname: </label>
            <input type="text" name="lastname" class="form-control <?php if (isset($data['lastname_err'])) (!empty($data['lastname_err'])) ? 'invalid' : ''; ?> value="<?php if (isset($data['lastname'])) echo $data['lastname']; ?>">
            <span class="invalid-response"><?php if (isset($data['lastname_err'])) echo $data['lastname_err']; ?></span>

            <label for="username">Username: </label>
            <input type="text" name="username" class="form-control <?php if (isset($data['username_err'])) (!empty($data['username_err'])) ? 'invalid' : ''; ?> value="<?php if (isset($data['username'])) echo $data['username']; ?>">
            <span class="invalid-response"><?php if (isset($data['username_err'])) echo $data['username_err']; ?></span>

            <label for="email">Email: </label>
            <input type="email" name="email" class="form-control <?php if (isset($data['email_err'])) (!empty($data['email_err'])) ? 'invalid' : ''; ?> value="<?php if (isset($data['email'])) echo $data['email']; ?>">
            <span class="invalid-response"><?php if (isset($data['email_err'])) echo $data['email_err']; ?></span>

            <label for="password">Password: </label>
            <input type="password" name="password" class="form-control <?php if (isset($data['password_err'])) (!empty($data['password_err'])) ? 'invalid' : ''; ?> value="<?php if (isset($data['password'])) echo $data['password']; ?>">
            <span class="invalid-response"><?php if (isset($data['password_err'])) echo $data['password_err']; ?></span>

            <label for="rppassword">Repeat Password: </label>
            <input type="password" name="repeat-password" class="form-control <?php if (isset($data['password-repeat_err'])) (!empty($data['password-repeat_err'])) ? 'invalid' : ''; ?> value="<?php if (isset($data['password-repeat'])) echo $data['password-repeat']; ?>">
            <span class="invalid-response"><?php if (isset($data['password-repeat_err'])) echo $data['password-repeat_err']; ?></span>

            <input class="register-btn" type="submit" name="submit" value="submit">

        </div>
    </form>
</div>



