<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">

    <title>Shared Gallery</title>
    <link rel="stylesheet" href="<?php echo \App\Core\Config::config('url') ?>/public/css/style.css" type="text/css" />
</head>
<body>
<div class="head-nav-wrapper">
    <h1 class="head-wrapper"><a class="link-href-wrapper" href="<?php echo SITE_PATH;?>/HomeController/index">Shared Gallery</a></h1>
    <?php if (isset($_SESSION) && isset($_SESSION['username'])) {
         require dirname(__DIR__) . '/layouts/navbar.phtml';
    } else {
        require dirname(__DIR__) . '/layouts/navbar.phtml';
    }
    ?>

</div>

<div class="container">



<?php require dirname(__DIR__) . '/layouts/footer.phtml'; ?>